# Generated by Django 4.2.4 on 2024-03-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=100)),
                ('confirmation_no', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
