# Generated by Django 4.2.4 on 2024-03-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
