# Generated by Django 4.2.4 on 2023-10-01 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Faculty', '0007_alter_kcseresults_grade_alter_kcseresults_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcseresults',
            name='grade',
            field=models.CharField(choices=[('D+', 'D+'), ('D-', 'D-'), ('A', 'A'), ('C+', 'C+'), ('A-', 'A-'), ('B+', 'B+'), ('C', 'C'), ('B', 'B'), ('E', 'E'), ('D', 'D'), ('C-', 'C-'), ('B-', 'B-')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kcseresults',
            name='subject',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('French', 'French'), ('Biology', 'Biology'), ('Mathematics', 'Mathematics'), ('English', 'English'), ('Drawing and Design', 'Drawing and Design'), ('Geography', 'Geography'), ('Building and Construction', 'Building and Construction'), ('Physics', 'Physics'), ('Computer Studies', 'Computer Studies'), ('Chemistry', 'Chemistry'), ('Home Science', 'Home Science'), ('Christian Religious Education', 'Christian Religious Education'), ('Business Studies', 'Business Studies'), ('Kiswahili', 'Kiswahili')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='answers_questions_clearly',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='asks_questions_of_class',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='available_to_students_after_class',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='encourages_questions_and_comments',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='explains_concepts_clearly',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='explains_how_each_topic_fits_in',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='facilitates_discussions_during_lecture',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gestures_while_speaking',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gives_multiple_examples',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gives_preliminary_overview_of_lecture',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='moves_about_while_lecturing',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='points_out_practical_applications',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='proceeds_at_good_pace_for_topic',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='projects_confidence',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='promotes_critical_thinking',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='repeats_difficult_ideas',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='shows_facial_expression',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='signals_transition_to_new_topic',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='speaks_expressively_or_emphatically',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='states_lecture_objectives',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='stays_on_theme_of_lecture',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='stresses_important_concepts',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='ties_in_primary_objectives_of_the_course',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='uses_concrete_examples_of_concepts',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='uses_humor',
            field=models.CharField(choices=[('Good', 'Good'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Adequate', 'Adequate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='addressed_to',
            field=models.CharField(choices=[('DEAN', 'DEAN'), ('FINANCE', 'FINANCE'), ('ADMIN', 'ADMIN'), ('LEC', 'LEC'), ('HOD', 'HOD'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=100),
        ),
        migrations.CreateModel(
            name='UnitSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_understanding', models.IntegerField()),
                ('approved', models.CharField(default='1', max_length=1)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.unit')),
            ],
        ),
    ]
