# Generated by Django 4.2.4 on 2023-10-08 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Faculty', '0013_remove_lecturerevaluation_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcseresults',
            name='grade',
            field=models.CharField(choices=[('B+', 'B+'), ('C+', 'C+'), ('D', 'D'), ('B-', 'B-'), ('C', 'C'), ('A', 'A'), ('D+', 'D+'), ('A-', 'A-'), ('C-', 'C-'), ('D-', 'D-'), ('B', 'B'), ('E', 'E')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kcseresults',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Business Studies', 'Business Studies'), ('Biology', 'Biology'), ('Computer Studies', 'Computer Studies'), ('English', 'English'), ('Agriculture', 'Agriculture'), ('French', 'French'), ('Christian Religious Education', 'Christian Religious Education'), ('Drawing and Design', 'Drawing and Design'), ('Building and Construction', 'Building and Construction'), ('Mathematics', 'Mathematics'), ('Geography', 'Geography'), ('Home Science', 'Home Science'), ('Kiswahili', 'Kiswahili')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='answers_questions_clearly',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='asks_questions_of_class',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='available_to_students_after_class',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='encourages_questions_and_comments',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='explains_concepts_clearly',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='explains_how_each_topic_fits_in',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='facilitates_discussions_during_lecture',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gestures_while_speaking',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gives_multiple_examples',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gives_preliminary_overview_of_lecture',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='moves_about_while_lecturing',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='points_out_practical_applications',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='proceeds_at_good_pace_for_topic',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='projects_confidence',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='promotes_critical_thinking',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='repeats_difficult_ideas',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='shows_facial_expression',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='signals_transition_to_new_topic',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='speaks_expressively_or_emphatically',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='states_lecture_objectives',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='stays_on_theme_of_lecture',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='stresses_important_concepts',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='ties_in_primary_objectives_of_the_course',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='uses_concrete_examples_of_concepts',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='uses_humor',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Poor', 'Poor'), ('Too Much', 'Too Much'), ('Excellent', 'Excellent'), ('Good', 'Good')], max_length=100),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='addressed_to',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STUDENT', 'STUDENT'), ('LEC', 'LEC'), ('HOD', 'HOD'), ('FINANCE', 'FINANCE'), ('DEAN', 'DEAN')], default='STUDENT', max_length=100),
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
