# Generated by Django 4.2.4 on 2024-02-25 16:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0025_alter_kcseresults_grade_alter_kcseresults_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('addressed_to', models.CharField(choices=[('HOD', 'HOD'), ('ADMIN', 'ADMIN'), ('LEC', 'LEC'), ('FINANCE', 'FINANCE'), ('DEAN', 'DEAN'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='kcseresults',
            name='grade',
            field=models.CharField(choices=[('B', 'B'), ('E', 'E'), ('B+', 'B+'), ('C', 'C'), ('C+', 'C+'), ('B-', 'B-'), ('A', 'A'), ('D+', 'D+'), ('D-', 'D-'), ('A-', 'A-'), ('C-', 'C-'), ('D', 'D')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kcseresults',
            name='subject',
            field=models.CharField(choices=[('Biology', 'Biology'), ('French', 'French'), ('Agriculture', 'Agriculture'), ('Computer Studies', 'Computer Studies'), ('Physics', 'Physics'), ('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Christian Religious Education', 'Christian Religious Education'), ('Business Studies', 'Business Studies'), ('Drawing and Design', 'Drawing and Design'), ('Building and Construction', 'Building and Construction'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Home Science', 'Home Science'), ('Geography', 'Geography')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='answers_questions_clearly',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='asks_questions_of_class',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='available_to_students_after_class',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='encourages_questions_and_comments',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='explains_concepts_clearly',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='explains_how_each_topic_fits_in',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='facilitates_discussions_during_lecture',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gestures_while_speaking',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gives_multiple_examples',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='gives_preliminary_overview_of_lecture',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='moves_about_while_lecturing',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='points_out_practical_applications',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='proceeds_at_good_pace_for_topic',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='projects_confidence',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='promotes_critical_thinking',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='repeats_difficult_ideas',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='shows_facial_expression',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='signals_transition_to_new_topic',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='speaks_expressively_or_emphatically',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='states_lecture_objectives',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='stays_on_theme_of_lecture',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='stresses_important_concepts',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='ties_in_primary_objectives_of_the_course',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='uses_concrete_examples_of_concepts',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturerevaluation',
            name='uses_humor',
            field=models.CharField(choices=[('Adequate', 'Adequate'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('Poor', 'Poor'), ('Too Much', 'Too Much')], max_length=100),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='addressed_to',
            field=models.CharField(choices=[('HOD', 'HOD'), ('ADMIN', 'ADMIN'), ('LEC', 'LEC'), ('FINANCE', 'FINANCE'), ('DEAN', 'DEAN'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=100),
        ),
    ]
