# Generated by Django 4.2.4 on 2024-03-10 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_pesapal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paid_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_reference',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
