# Generated by Django 4.2.4 on 2023-09-30 17:49

import Student.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Faculty', '0006_alter_kcseresults_grade_alter_kcseresults_subject_and_more'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProvisionalTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.FileField(upload_to=Student.models.transcript_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.year')),
            ],
            options={
                'verbose_name_plural': 'Transcripts',
            },
        ),
    ]
