# Generated by Django 4.2.4 on 2023-09-30 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0004_viewedexamcards_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedexamcards',
            name='view_id',
        ),
        migrations.AddField(
            model_name='viewedexamcards',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
