# Generated by Django 4.2.4 on 2023-09-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_remove_viewedexamcards_view_id_viewedexamcards_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewedexamcards',
            name='exam_card_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.examcards'),
            preserve_default=False,
        ),
    ]
