# Generated by Django 4.2.4 on 2023-10-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_remove_viewedexamcards_exam_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedexamcards',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='viewprovisionaltranscript',
            name='year',
        ),
    ]
