# Generated by Django 4.2.4 on 2023-10-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_delete_viewprovisionaltranscript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewedExamCards',
        ),
    ]
