# Generated by Django 4.2.4 on 2024-03-06 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0027_alter_events_addressed_to_alter_kcseresults_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0012_students_fee_balance_students_total_billed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition', models.FloatField(default=0.0)),
                ('student_activity', models.FloatField(default=0.0)),
                ('student_id_card', models.FloatField(default=0.0)),
                ('computer_fee', models.FloatField(default=0.0)),
                ('examination_fee', models.FloatField(default=0.0)),
                ('internet_connectivity', models.FloatField(default=0.0)),
                ('kuccps_placement_fee', models.FloatField(default=0.0)),
                ('library_fee', models.FloatField(default=0.0)),
                ('maintenance_fee', models.FloatField(default=0.0)),
                ('medical_fee', models.FloatField(default=0.0)),
                ('student_organization', models.FloatField(default=0.0)),
                ('quality_assurance_fee', models.FloatField(default=0.0)),
                ('registration_fee', models.FloatField(default=0.0)),
                ('amenity_fee', models.FloatField(default=0.0)),
                ('attachment', models.FloatField(default=0.0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.stage')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('debit', models.FloatField(default=0.0)),
                ('credit', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
