# Generated by Django 4.2.4 on 2024-03-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_feestructure_feestatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
