# Generated by Django 4.2.4 on 2024-03-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_feestructure_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestatement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
