# Generated by Django 4.2.4 on 2024-02-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='message',
            new_name='error',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
