# Generated by Django 4.2.4 on 2024-02-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesapal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
