# Generated by Django 4.2.4 on 2024-02-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pesapal', '0002_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
