# Generated by Django 4.2.4 on 2024-03-10 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pesapal', '0004_transaction_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='STDTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('reference', models.CharField(max_length=100)),
                ('mercharnt_reference', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('INVALID', 'INVALID')], max_length=100)),
                ('payment_method', models.CharField(max_length=24)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mercharnt_reference', 'reference')},
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
