from django.urls import path

from Dean.views.views import *

urlpatterns = [
    path('Dashboard/', Dashboard.as_view(), name='DeanDashBoard'),
    path('CreateProfile/', CreateProfile.as_view(), name='DeanCreateProfile'),
    path('SaveProfile/', SaveProfile.as_view(), name='DeanSaveProfile'),
    path('StudentsProfile/', StudentsProfile.as_view(), name='DeanStudentsProfile'),
    path('StudentDetails/<pk>', StudentDetails.as_view(), name='DeanStudentDetails'),
    path('ListCourses/', ListCourses.as_view(), name='DeanListCourses'),
    path('ListStages/', ListStages.as_view(), name='DeanListStages'),
    path('ApplicationRequests/', ApplicationRequests.as_view(), name='DeanApplicationRequests'),
    path('UnitApplication/', UnitApplication.as_view(), name='DeanUnitApplication'),
    path('SubmitApplication/', SubmitApplication.as_view(), name='DeanSubmitApplication'),
    path('MyUnits/', MyUnits.as_view(), name='DeanMyUnits'),
    path('ListDepartments/', ListDepartments.as_view(), name='DeanListDepartments'),
    path('UpdateProfile/', UpdateProfile.as_view(), name='DeanUpdateProfile'),
    path('UserManagement/', UserManagement.as_view(), name='DeanUserManagement'),
    path('CreateUserAccount/', CreateUser.as_view(), name='DeanCreateUserAccount'),
    path('SaveUserAccount/', SaveUserAccount.as_view(), name='DeanSaveUserAccount'),
    path('CreateCourse/', CreateCourse.as_view(), name='DeanCreateCourse'),
    path('SaveCourse/', SaveCourse.as_view(), name='DeanSaveCourse'),
    path('DeleteUserAccount/<pk>', DeleteUserAccount.as_view(), name='DeanDeleteUserAccount'),
    path('ConfirmDelete/<pk>', ConfirmDelete.as_view(), name='DeanConfirmDelete'),
    path('ResetPassword/<pk>', ResetPassword.as_view(), name='DeanResetPassword'),
    path('SavePassword/<pk>', SavePassword.as_view(), name='DeanSavePassword'),
    path('EditCourse/<pk>', EditCourse.as_view(), name='DeanEditCourse'),
    path('UpdateCourse/<pk>', UpdateCourse.as_view(), name='DeanUpdateCourse'),
    path('CreateStage/', CreateStage.as_view(), name='DeanCreateStage'),
    path('SaveStage/', SaveStage.as_view(), name='DeanSaveStage'),
    path('UpdateDean/', UpdateDean.as_view(), name='UpdateDean'),
    path('YearsOfStudy/', YearsOfStudy.as_view(), name='DeanYearsOfStudy'),
    path('GenerateProvisionalTranscripts/', GenerateProvisionalTranscripts.as_view(), name='DeanGenerateProvisionalTranscripts'),
    path('ApproveResults/<student>/<year_of_study>', ApproveResults.as_view(), name='DeanApproveResults'),
    path('StudentResults/<pk>', StudentResults.as_view(), name='DeanStudentResults'),
    path('EditStage/<pk>', EditStage.as_view(), name='DeanEditStage'),
    path('UpdateStage/<pk>', UpdateStage.as_view(), name='DeanUpdateStage'),
    path('ApproveApplication/<pk>', ApproveApplication.as_view(), name='DeanApproveApplication'),
    path('RejectApplication/<pk>', RejectApplication.as_view(), name='DeanRejectApplication'),
    # path('EditUserAccount/<pk>', EditUserAccount, name='DeanEditUserAccount'),
    path('ListUnits/<pk>', ListUnits.as_view(), name='DeanListUnits'),
    # path('UpdateUserProfile/<pk>', UpdateUserProfile, name='DeanUpdateUserProfile'),
    path('activate_deactivate/<pk>', ActivateDeactivate.as_view(), name='DeanActivateDeactivateUser'),
    path('TransferRequests/', TransferRequests.as_view(), name='TransferRequests'),
    path('KsceResults/<pk>', KsceResults.as_view(), name='KsceResults'),
    path('ApproveTransferRequest/<pk>', ApproveTransferRequest.as_view(), name='ApproveTransferRequest'),
    path('ConfirmTransApproval/<pk>', ConfirmTransApproval.as_view(), name='ConfirmTransApproval'),
    path('RejectTransferRequest/<pk>', RejectTransferRequest.as_view(), name='RejectTransferRequest'),
    path('ConfirmTransRejection/<pk>', ConfirmTransRejection.as_view(), name='ConfirmTransRejection'),
    path('LeaveRequest/', LeaveRequest.as_view(), name='DeanLeaveRequests'),
    path('ApproveLeaveRequest/<pk>', ApproveLeaveRequest.as_view(), name='DeanApproveLeaveRequest'),
    path('RejectLeaveRequest/<pk>', RejectLeaveRequest.as_view(), name='DeanRejectLeaveRequest'),
]
